# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_auto_20180117_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('C', 'Concluída'), ('P', 'Em progresso'), ('CD', 'Cancelada')], default='P', max_length=5, verbose_name='Status'),
        ),
    ]
